apiVersion: v1
kind: Service
metadata:
  {{ if .Values.service.fixedName -}}
  name: {{ .Values.service.fixedName }}
  {{- else -}}
  name: {{ template "jupyterScala.fullname" . }}
  {{- end }}
  labels:
    app: {{ template "jupyterScala.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ template "jupyterScala.fullname" . }}
  selector:
    app: {{ template "jupyterScala.name" . }}
    release: {{ .Release.Name }}
